source "https://rubygems.org"

gem "debug"
gem "minitest"
gem "minitest-difftastic"
gem "minitest-reporters", github: "andyw8/minitest-reporters", branch: "andyw8/clean-reporter"
gem "mocha"
gem "rake"
gem "standard"
gem "standard-minitest"
gem "irb"
