name: Ruby

on: [push, pull_request]
jobs:
  test:
    if: github.repository == 'andyw8/ruby-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run checks
        run: bundle exec rake
